name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0

      # Setup bun
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      - run: bunx nx start-ci-run --distribute-on="3 linux-medium-bun" --stop-agents-after="build"

      - run: bun install --frozen-lockfile
      - run: bunx cypress install
      - uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: bunx nx-cloud record -- echo Hello World
      # When you enable task distribution, run the e2e-ci task instead of e2e
      - run: bunx nx affected -t lint
      - run: bunx nx affected -t test -c ci
      - run: bunx nx affected -t build -c production
      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      - run: bunx nx fix-ci
        if: always()
      # Upload code coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
